function CodeDefine() { 
this.def = new Array();
this.def["runModel"] = {file: "ert_main_c.html",line:16,type:"var"};
this.def["stopSem"] = {file: "ert_main_c.html",line:17,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_c.html",line:18,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_c.html",line:19,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_c.html",line:20,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_c.html",line:21,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_c.html",line:22,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_c.html",line:23,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_c.html",line:67,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_c.html",line:73,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:92,type:"fcn"};
this.def["trigger_test_B"] = {file: "trigger_test_c.html",line:26,type:"var"};
this.def["trigger_test_DW"] = {file: "trigger_test_c.html",line:29,type:"var"};
this.def["trigger_test_PrevZCX"] = {file: "trigger_test_c.html",line:32,type:"var"};
this.def["trigger_test_M_"] = {file: "trigger_test_c.html",line:35,type:"var"};
this.def["trigger_test_M"] = {file: "trigger_test_c.html",line:36,type:"var"};
this.def["rt_modd_snf"] = {file: "trigger_test_c.html",line:37,type:"fcn"};
this.def["trigger_test_step"] = {file: "trigger_test_c.html",line:73,type:"fcn"};
this.def["trigger_test_initialize"] = {file: "trigger_test_c.html",line:177,type:"fcn"};
this.def["trigger_test_terminate"] = {file: "trigger_test_c.html",line:273,type:"fcn"};
this.def["B_trigger_test_T"] = {file: "trigger_test_h.html",line:86,type:"type"};
this.def["DW_trigger_test_T"] = {file: "trigger_test_h.html",line:95,type:"type"};
this.def["PrevZCX_trigger_test_T"] = {file: "trigger_test_h.html",line:100,type:"type"};
this.def["codertarget_linux_blocks_Digi_T"] = {file: "trigger_test_types_h.html",line:30,type:"type"};
this.def["struct_T_trigger_test_T"] = {file: "trigger_test_types_h.html",line:39,type:"type"};
this.def["struct_T_trigger_test_b_T"] = {file: "trigger_test_types_h.html",line:51,type:"type"};
this.def["P_trigger_test_T"] = {file: "trigger_test_types_h.html",line:56,type:"type"};
this.def["RT_MODEL_trigger_test_T"] = {file: "trigger_test_types_h.html",line:59,type:"type"};
this.def["trigger_test_P"] = {file: "trigger_test_data_c.html",line:24,type:"var"};
this.def["chunk_T"] = {file: "multiword_types_h.html",line:27,type:"type"};
this.def["uchunk_T"] = {file: "multiword_types_h.html",line:28,type:"type"};
this.def["long_T"] = {file: "multiword_types_h.html",line:33,type:"type"};
this.def["int64m_T"] = {file: "multiword_types_h.html",line:40,type:"type"};
this.def["cint64m_T"] = {file: "multiword_types_h.html",line:45,type:"type"};
this.def["uint64m_T"] = {file: "multiword_types_h.html",line:49,type:"type"};
this.def["cuint64m_T"] = {file: "multiword_types_h.html",line:54,type:"type"};
this.def["int96m_T"] = {file: "multiword_types_h.html",line:58,type:"type"};
this.def["cint96m_T"] = {file: "multiword_types_h.html",line:63,type:"type"};
this.def["uint96m_T"] = {file: "multiword_types_h.html",line:67,type:"type"};
this.def["cuint96m_T"] = {file: "multiword_types_h.html",line:72,type:"type"};
this.def["int128m_T"] = {file: "multiword_types_h.html",line:76,type:"type"};
this.def["cint128m_T"] = {file: "multiword_types_h.html",line:81,type:"type"};
this.def["uint128m_T"] = {file: "multiword_types_h.html",line:85,type:"type"};
this.def["cuint128m_T"] = {file: "multiword_types_h.html",line:90,type:"type"};
this.def["int160m_T"] = {file: "multiword_types_h.html",line:94,type:"type"};
this.def["cint160m_T"] = {file: "multiword_types_h.html",line:99,type:"type"};
this.def["uint160m_T"] = {file: "multiword_types_h.html",line:103,type:"type"};
this.def["cuint160m_T"] = {file: "multiword_types_h.html",line:108,type:"type"};
this.def["int192m_T"] = {file: "multiword_types_h.html",line:112,type:"type"};
this.def["cint192m_T"] = {file: "multiword_types_h.html",line:117,type:"type"};
this.def["uint192m_T"] = {file: "multiword_types_h.html",line:121,type:"type"};
this.def["cuint192m_T"] = {file: "multiword_types_h.html",line:126,type:"type"};
this.def["int224m_T"] = {file: "multiword_types_h.html",line:130,type:"type"};
this.def["cint224m_T"] = {file: "multiword_types_h.html",line:135,type:"type"};
this.def["uint224m_T"] = {file: "multiword_types_h.html",line:139,type:"type"};
this.def["cuint224m_T"] = {file: "multiword_types_h.html",line:144,type:"type"};
this.def["int256m_T"] = {file: "multiword_types_h.html",line:148,type:"type"};
this.def["cint256m_T"] = {file: "multiword_types_h.html",line:153,type:"type"};
this.def["uint256m_T"] = {file: "multiword_types_h.html",line:157,type:"type"};
this.def["cuint256m_T"] = {file: "multiword_types_h.html",line:162,type:"type"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:31,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:79,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:90,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:138,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:31,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:79,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:34,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:40,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:52,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:58,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:64,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:70,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:41,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:48,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:55,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:27,type:"type"};
this.def["rtDataTypeSizes"] = {file: "trigger_test_dt_h.html",line:23,type:"var"};
this.def["rtDataTypeNames"] = {file: "trigger_test_dt_h.html",line:42,type:"var"};
this.def["rtBTransitions"] = {file: "trigger_test_dt_h.html",line:61,type:"var"};
this.def["rtBTransTable"] = {file: "trigger_test_dt_h.html",line:79,type:"var"};
this.def["rtPTransitions"] = {file: "trigger_test_dt_h.html",line:85,type:"var"};
this.def["rtPTransTable"] = {file: "trigger_test_dt_h.html",line:90,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "/";
var isPC = false;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["trigger_test_c.html"] = "../trigger_test.c";
	this.html2Root["trigger_test_c.html"] = "trigger_test_c.html";
	this.html2SrcPath["trigger_test_h.html"] = "../trigger_test.h";
	this.html2Root["trigger_test_h.html"] = "trigger_test_h.html";
	this.html2SrcPath["trigger_test_private_h.html"] = "../trigger_test_private.h";
	this.html2Root["trigger_test_private_h.html"] = "trigger_test_private_h.html";
	this.html2SrcPath["trigger_test_types_h.html"] = "../trigger_test_types.h";
	this.html2Root["trigger_test_types_h.html"] = "trigger_test_types_h.html";
	this.html2SrcPath["trigger_test_data_c.html"] = "../trigger_test_data.c";
	this.html2Root["trigger_test_data_c.html"] = "trigger_test_data_c.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "multiword_types_h.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["trigger_test_dt_h.html"] = "../trigger_test_dt.h";
	this.html2Root["trigger_test_dt_h.html"] = "trigger_test_dt_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","trigger_test_c.html","trigger_test_h.html","trigger_test_private_h.html","trigger_test_types_h.html","trigger_test_data_c.html","multiword_types_h.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","trigger_test_dt_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html"];
